from .ofa import OFAModel, ofa_base_architecture, ofa_large_architecture, ofa_huge_architecture
from .ofa_speech import OFASpeech, ofa_speech_base_architecture, ofa_speech_large_architecture
from .ofa_classification import OFAClassificationModel, ofa_classification_base_architecture, ofa_classification_large_architecture, ofa_classification_huge_architecture