from .caption import CaptionTask
from .image_gen import ImageGenTask
from .refcoco import RefcocoTask
from .snli_ve import SnliVeTask
from .vqa_gen import VqaGenTask
from .seg import SegTask
from .report_vqa import ReportVqaTask
from .report_mlm import ReportMLMTask
from .vqa_gen_classification import VqaGenClsTask
